blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/juliangumenita/simple-effing-primitive-layout/discussions
    about: Please discuss non bug-related topics there
